const fontFamilies = [
    'Arial',
    'Roboto',
    'Palatino Linotype',
    'Book Antiqua',
    'Palatino',
    'Times New Roman',
    'Times Roman',
    'Times',
    'Helvetica',
    'Arial Black',
    'Gadget',
    'Comic Sans MS',
    'Apple Chancery',
    'Papyrus',
    'Impact',
    'Charcoal',
    'Lucida Sans Unicode',
    'Lucida Grande',
    'Tahoma',
    'Geneva',
    'TrebuchetMS',
    'Verdana',
    'Courier',
    'Courier New',
    'Lucida Console',
    'Monaco',
    'Osaka',
    'Yu Gothic',
    'Yu Gothic Medium',
    'YuGo-Medium',
    'Yu Mincho',
    'Yu Mincho Regular',
    'YuMin-Medium',
    'YuKyo-Medium',
    'Meiryo',
    'MS PMincho',
    'MS PGothic',
    'mplus-2p-regular',
    'HiraginoSans-W4',
    'HiraMaruProN-W4',
    'HiraMinProN-W3'
];

export default fontFamilies