const fontFamilies = [
    'Arial',
    'Arial Black',
    'Arial Narrow',
    'Calibri',
    'Candara',
    'Century Gothic',
    'Futura',
    'Geneva',
    'Gill Sans',
    'Helvetica',
    'Impact',
    'Lucida Grande',
    'Roboto',
    'Optima',
    'Segoe UI',
    'Tahoma',
    'TrebuchetMS',
    'Verdana',

    'Big Caslon',
    'Book Antiqua',
    'Cambria',
    'Didot',
    'Garamond',
    'Georgia',
    'Hoefler Text',
    'Lucida Bright',
    'Palatino',
    'Palatino Linotype',
    'Baskerville',
    'Times New Roman',

    'Apple Chancery',
    'Brush Script MT',
    'Charcoal',
    'Comic Sans MS',
    'Courier',
    'Courier New',
    'Copperplate',
    'Gadget',
    'Lucida Sans Unicode',
    'Lucida Console',
    'Monaco',
    'Papyrus',
];

export default fontFamilies